# Generated by Django 4.2.13 on 2024-06-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.CharField(max_length=6, unique=True)),
                ('hospitalID', models.CharField(max_length=6, unique=True)),
                ('interview_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infuenza_vaccine', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('covid_19', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('number_of_covid_doses', models.IntegerField()),
                ('covid_19_test_verified_card', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('covid_19_test', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('covid_19_result', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEMFORM.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='SpecimenCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_collected', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('type_of_spacimen_collected', models.CharField(max_length=100)),
                ('date_of_specimen_collection', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEMFORM.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningQuestionaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_of_fever_report', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('cough', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('onset_of_symptoms', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('hospitalizedd', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('onset_date', models.DateField()),
                ('interview_type', models.CharField(choices=[('1', 'SARI surveillance'), ('2', 'Outbreak'), ('1', 'ILI surveillance')], max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEMFORM.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_respiratory_disease', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('neurological_disease', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('newly_diagonised_TB', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('prior_TB', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('HIV_AIDS', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('chardiac_heart_disease', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('liver_disease', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('renal_disease', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('diabetess', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('asthma', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('cancer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('sickle_cell', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('rickets', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEMFORM.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('mode_of_measurement', models.CharField(choices=[('oral', 'Oral'), ('auxiliary', 'Auxiliary')], max_length=100)),
                ('respiratory_rate', models.CharField(max_length=100)),
                ('oxygent_saturation', models.CharField(max_length=100)),
                ('type_of_oxygen', models.CharField(choices=[('room_air', 'Room Air'), ('on_supplemental_oxygen', 'On Supplemental Oxygen')], max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEMFORM.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='FinalOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_outcome', models.CharField(choices=[('1', 'Discharge from hospital alive'), ('death', 'Death'), ('refused_treatment', 'Refuse hospital tratment'), ('absconded', 'Absconded')], max_length=100)),
                ('refered_facility_name', models.CharField(max_length=100)),
                ('date_of_final_outcome', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEMFORM.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseSverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted_to_ICU', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('recieved_mechanicla_ventilation', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEMFORM.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='DemographicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('patients_age_in_months', models.IntegerField()),
                ('patients_age_in_years', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEMFORM.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentIllnessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onset_date', models.DateField()),
                ('date_for_hospital_admition', models.DateField()),
                ('date_of_outpatient', models.DateField()),
                ('wheezing', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('sore_throat', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('difficulty_in_breathing', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('rhinorrhea', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('chest_pain', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('diarrhea', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('vomiting', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('muscles_aches', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('chills', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('lack_of_appetite', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('convulsions', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEMFORM.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='ChildrenInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unable_to_drink', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('vomits', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('stridor', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('grunting', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('nasal_flaring', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('chest_in_drawing', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('lethargic', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('unconcious', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KEMFORM.patientdetails')),
            ],
        ),
    ]
