# Generated by Django 4.2.13 on 2024-06-20 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KEMFORM', '0003_screeningquestionaire_body_temperature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentillnessinfo',
            name='date_for_hospital_admition',
        ),
        migrations.RemoveField(
            model_name='vaccination',
            name='covid_19_test',
        ),
        migrations.AddField(
            model_name='currentillnessinfo',
            name='date_for_hospital_admision',
            field=models.DateField(null=True, verbose_name='Date of hospital admission(for SARI cases)'),
        ),
        migrations.AddField(
            model_name='riskfactors',
            name='malnutrition',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], default=datetime.datetime(2024, 6, 20, 11, 1, 10, 2286, tzinfo=datetime.timezone.utc), max_length=10, verbose_name='Malnutrition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vaccination',
            name='influenza_verification',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], default=1, max_length=10, verbose_name='Was this verified using a vaccination card?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='childreninfo',
            name='chest_in_drawing',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Chest in-dwrawing (reaction under ribcage on inspiration):'),
        ),
        migrations.AlterField(
            model_name='childreninfo',
            name='grunting',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Grunting:'),
        ),
        migrations.AlterField(
            model_name='childreninfo',
            name='lethargic',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Lethargic:'),
        ),
        migrations.AlterField(
            model_name='childreninfo',
            name='nasal_flaring',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Nasal flaring:'),
        ),
        migrations.AlterField(
            model_name='childreninfo',
            name='stridor',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Stridor:'),
        ),
        migrations.AlterField(
            model_name='childreninfo',
            name='unable_to_drink',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Unable to drink or breastfeed at all'),
        ),
        migrations.AlterField(
            model_name='childreninfo',
            name='unconcious',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Unconscious(comatos, not awake):'),
        ),
        migrations.AlterField(
            model_name='childreninfo',
            name='vomits',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Vomits everything'),
        ),
        migrations.AlterField(
            model_name='currentillnessinfo',
            name='date_of_outpatient',
            field=models.DateField(verbose_name='Date seen in out-patient(for ILI cases)'),
        ),
        migrations.AlterField(
            model_name='currentillnessinfo',
            name='onset_date',
            field=models.DateField(verbose_name='Date of onset of current illness'),
        ),
        migrations.AlterField(
            model_name='demographicinfo',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=100, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='demographicinfo',
            name='hospital_name',
            field=models.CharField(max_length=100, verbose_name='Hospital:'),
        ),
        migrations.AlterField(
            model_name='demographicinfo',
            name='patients_age_in_months',
            field=models.IntegerField(verbose_name='Age in months(for children below 59 months)'),
        ),
        migrations.AlterField(
            model_name='demographicinfo',
            name='patients_age_in_years',
            field=models.IntegerField(verbose_name='age in years '),
        ),
        migrations.AlterField(
            model_name='diseasesverity',
            name='admitted_to_ICU',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Been admitted to ICU/HDU?'),
        ),
        migrations.AlterField(
            model_name='diseasesverity',
            name='recieved_mechanicla_ventilation',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Received mechanical ventilation?'),
        ),
        migrations.AlterField(
            model_name='finaloutcome',
            name='date_of_final_outcome',
            field=models.DateField(verbose_name='Date of final outcome?'),
        ),
        migrations.AlterField(
            model_name='finaloutcome',
            name='final_outcome',
            field=models.CharField(choices=[('discharged_alive', 'Discharge from hospital alive'), ('death', 'Death'), ('refused_treatment', 'Refuse hospital tratment'), ('absconded', 'Absconded')], max_length=100, verbose_name='What was the final outcome?'),
        ),
        migrations.AlterField(
            model_name='finaloutcome',
            name='refered_facility_name',
            field=models.CharField(max_length=100, verbose_name='Specify name of the facility'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='hospitalID',
            field=models.CharField(max_length=6, unique=True, verbose_name='Hospital ID number'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='interview_date',
            field=models.DateField(auto_now_add=True, verbose_name='Interview date'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='patientId',
            field=models.CharField(max_length=6, unique=True, verbose_name='Patient unique ID number'),
        ),
        migrations.AlterField(
            model_name='physicalexamination',
            name='mode_of_measurement',
            field=models.CharField(choices=[('oral', 'Oral'), ('auxiliary', 'Auxiliary'), ('forehead', 'Forehead thermometer gun')], max_length=100, verbose_name='Mode of temperature measurement'),
        ),
        migrations.AlterField(
            model_name='physicalexamination',
            name='oxygent_saturation',
            field=models.CharField(max_length=100, verbose_name='Oxygen saturation %:'),
        ),
        migrations.AlterField(
            model_name='physicalexamination',
            name='respiratory_rate',
            field=models.CharField(max_length=100, verbose_name='Respiratory rate: ( breaths per minute<strong><i>(count for full minute)'),
        ),
        migrations.AlterField(
            model_name='physicalexamination',
            name='temperature',
            field=models.FloatField(verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='physicalexamination',
            name='type_of_oxygen',
            field=models.CharField(choices=[('room_air', 'Room Air'), ('on_supplemental_oxygen', 'On Supplemental Oxygen')], max_length=100, verbose_name='Type of oxygen'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='HIV_AIDS',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='HIV/AIDS'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='asthma',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Asthma'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='cancer',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Cancer (currently or in the past 12 months)'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='chardiac_heart_disease',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Chronic cardiac/heart disease'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='chronic_respiratory_disease',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Chronic respiratory disease (not including asthma and TB)'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='diabetess',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Diabetes'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='liver_disease',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Chronic liver disease'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='neurological_disease',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Chronic neurological or neuromuscular disease'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='newly_diagonised_TB',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Newly diagnosed TB'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='prior_TB',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Prior TB'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='renal_disease',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Chronic renal disease'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='rickets',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Rickets'),
        ),
        migrations.AlterField(
            model_name='riskfactors',
            name='sickle_cell',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Sickle cell disease'),
        ),
        migrations.AlterField(
            model_name='screeningquestionaire',
            name='body_temperature',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='The patient has   measured fever greater than 38 ℃?'),
        ),
        migrations.AlterField(
            model_name='specimencollection',
            name='date_of_specimen_collection',
            field=models.DateField(verbose_name='Date of specimen collection'),
        ),
        migrations.AlterField(
            model_name='specimencollection',
            name='specimen_collected',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Was any specimen collected from this patient for influenza testing?'),
        ),
        migrations.AlterField(
            model_name='specimencollection',
            name='type_of_spacimen_collected',
            field=models.CharField(choices=[('nasal_swab', 'Nasal swab'), ('op', 'OP'), ('ip', 'IP'), ('ip/op', 'IP/OP')], max_length=100, verbose_name='Type of swab specimen collected?'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='covid_19',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Covid 19 Vaccine?'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='covid_19_result',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, verbose_name='If yes, what was the COVID-19 test result?'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='covid_19_test_verified_card',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Was this verified using a vaccination card or hospital records?'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='infuenza_vaccine',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('dont_know', "I don't know")], max_length=10, verbose_name='Influenza vaccine in the first twelve months?'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='number_of_covid_doses',
            field=models.IntegerField(verbose_name='If yes, how many doses of COVID-19 vaccine?'),
        ),
    ]
